database:
  host: 127.0.0.1
  port: :3306
  database: ali_cm
  username: root
  password: 
  log_queries: true
  timeout_seconds: 5

server:
  mode: debug
  port: localhost:3000
  read_timeout_seconds: 10
  write_timeout_seconds: 5
